### PR TITLE
chore: environment variable

### PR DESCRIPTION
**Pull request by husseinzaher**
Add all config to environment variable 
Add function `env()` to get environment variable

### CODE REVIEW

**Review by husseinzaher — COMMENTED** [review]
Please approve it

**Comment by icleitoncosta** [comment]
> Please approve it

This PR will break projects that are already running if updated

**Comment by husseinzaher** [comment]
> > Please approve it
> 
> This PR will break projects that are already running if updated

Why i make function that get the environment variable because i have 3 different environment

**Comment by renat473** [comment]
Hello @husseinzaher 

This change in the project will stop several projects that are in production from functioning.

For now, this PR will be kept open to check all changes made to the code and also inform the community of this change.

**Comment by husseinzaher** [comment]
Great, thanks for reply.

**Pull request closed without merging**
