### PR TITLE
fix: deleteMessage phone error

### PR DESCRIPTION
**Pull request by rcovery**

### CODE REVIEW

**Review by ghsgabriel — CHANGES_REQUESTED** [review]
Hi @rcovery 
,
This PR reverts a previous fix, but does not resolve all issues.

Today, a server middleware already handles the contacts (phone) considering isGroup and adds @g.us and @c.us if they don't exist. The middleware also considers arrays of contacts in this case.

We can't remove the foreach because today it's allowed to pass an array of contacts.

Also we cannot add @c.us and @g.us to the req.client.deleteChat/clearChat call as it can cause duplicate bugs: <phone>@c.us@c.us, as the middleware already adds them to all the phone array strings.

These were the bugs fixed earlier.


What exactly is the error you are trying to fix and how could I reproduce it? Maybe I can give you some suggestion for a solution, but the way it is currently I couldn't reproduce any error, either with contact alone, with array of contacts or for groups.

In addition, you committed fixes of several functions in a commit that would just be for deleteMessage. The ideal would be a PR for each fix, so it's even easier to test and talk about the individual solutions of the other fixes and we don't have to wait for everyone to be 100% to merge.

Thank you very much for your contribution.

**Comment by leohturbo** [comment]
> 

Maybe got it on mark unseen too. Check it please. Tks.

**Comment by leohturbo** [comment]
> Hi @rcovery , This PR reverts a previous fix, but does not resolve all issues.
> 
> Today, a server middleware already handles the contacts (phone) considering isGroup and adds @g.us and @c.us if they don't exist. The middleware also considers arrays of contacts in this case.
> 
> We can't remove the foreach because today it's allowed to pass an array of contacts.
> 
> Also we cannot add @c.us and @g.us to the req.client.deleteChat/clearChat call as it can cause duplicate bugs: @[c.us@c.us](mailto:c.us@c.us), as the middleware already adds them to all the phone array strings.
> 
> These were the bugs fixed earlier.
> 
> What exactly is the error you are trying to fix and how could I reproduce it? Maybe I can give you some suggestion for a solution, but the way it is currently I couldn't reproduce any error, either with contact alone, with array of contacts or for groups.
> 
> In addition, you committed fixes of several functions in a commit that would just be for deleteMessage. The ideal would be a PR for each fix, so it's even easier to test and talk about the individual solutions of the other fixes and we don't have to wait for everyone to be 100% to merge.
> 
> Thank you very much for your contribution.

Maybe have this duplication on mark-unseen too.

**Comment by icleitoncosta** [comment]
Closed this PR because problem is solved.

**Pull request closed without merging**
